databases:
  - name: Epedika
    databaseName: Epedika
    user: Epedika

services:
  - type: web
    name: Epedika
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Epedika.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Epedika
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4